name:          Guide de Code par @mdo
description:   Standards pour des fichiers HTML et CSS flexibles, durables et maintenables.
url:           http://pixelastic.github.io/code-guide/

markdown:      rdiscount
permalink:     pretty
pygments:      true